force-app/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entity__c/fields/HierarchySort__c.field-meta.xml
<CustomField>
    <fullName>HierarchySort__c</fullName>
    <label>Hierarchy Sort</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Entity__c/fields/LineDisplay__c.field-meta.xml
<CustomField>
    <fullName>LineDisplay__c</fullName>
    <label>Line Display</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entity__c/fields/ParentEntity__c.field-meta.xml
<CustomField>
    <fullName>ParentEntity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Entity</label>
    <referenceTo>Entity__c</referenceTo>
    <relationshipLabel>Subordinate Entities</relationshipLabel>
    <relationshipName>Entitites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EntityHierarchyMethods.cls
public class EntityHierarchyMethods {
//Write it the expensive way first
// EntityHierarchyMethods.ResetEntityHierarchy();
// 
	
    public static void ResetEntityHierarchy(){
    	EntityHierarchyMethods.IterateEntityHierarchy(null, 0, 0);
    }
    
    public static void IterateEntityHierarchy(ID parentID, integer iLevel, integer iHierarchySort){
        integer currentLevel=iLevel;
        integer currentHierarchySort=iHierarchySort;
        String p='';
		p=p.leftPad(currentLevel*5,'-');
        currentLevel++;
        List<Entity__c> iterateEntities = [SELECT Id, Name, Level__c, LineDisplay__c, ParentEntity__c FROM Entity__c WHERE ParentEntity__c=:parentId ORDER BY Name];
        for(Entity__c e : iterateEntities){
            currentHierarchySort++;
            System.debug('currentHierarchySort=' + currentHierarchySort + '  Name=' + e.Name);
			e.HierarchySort__c=currentHierarchySort;
            e.Level__c=currentLevel;
            e.LineDisplay__c=p + e.Name;
            update e;
    		EntityHierarchyMethods.IterateEntityHierarchy(e.Id, currentLevel, currentHierarchySort);
            
        }
        
    }
}