force-app/main/default/objects/Entity__c/Entity__c.object-meta.xml
<CustomObject>
    <label>Entity</label>
    <nameField>
        <label>Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KBCard__c/KBCard__c.object-meta.xml
<CustomObject>
    <description>KanBan cards for making program, projects, epics, features, &amp; user stories</description>
    <label>KBCard</label>
    <nameField>
        <label>KBCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KBCards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KBCard__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Imo Enterprises (IE)</fullName>
                <default>true</default>
                <label>Imo Enterprises (IE)</label>
            </value>
            <value>
                <fullName>Imo Apartments (LL)</fullName>
            </value>
            <value>
                <fullName>Imo Ice Cream &amp; Goods (IG)</fullName>
            </value>
            <value>
                <fullName>Imo Coffee &amp; Bookstore (CB)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/HierarchyPath__c.field-meta.xml
<CustomField>
    <fullName>HierarchyPath__c</fullName>
    <label>Hierarchy Path</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/KBCExtID__c.field-meta.xml
<CustomField>
    <fullName>KBCExtID__c</fullName>
    <label>KBCExtID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/ParentKBCard__c.field-meta.xml
<CustomField>
    <fullName>ParentKBCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent KBCard</label>
    <referenceTo>KBCard__c</referenceTo>
    <relationshipLabel>Child KBCards</relationshipLabel>
    <relationshipName>KBCards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1-Backlog</fullName>
            </value>
            <value>
                <fullName>2-In Progress</fullName>
            </value>
            <value>
                <fullName>3-Completed</fullName>
            </value>
            <value>
                <fullName>4-Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NA</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Business Plan</fullName>
            </value>
            <value>
                <fullName>Site Build</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Operating Documents</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KBCard__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <label>Program</label>
</RecordType>

force-app/main/default/classes/KBCardProcessorHierarchyPathTest.cls
@isTest
public class KBCardProcessorHierarchyPathTest {
	@testSetup 
    static void setup() {
		Id ProgramRTId = Schema.SObjectType.KBCard__c.getRecordTypeInfosByDeveloperName().get('Program').getRecordTypeId();
        Id parentProgramID1;
        Id parentProgramID2;
        //Update Level 1 - Program
        KBCard__c kbc=new KBCard__c();
        kbc.RecordTypeId=ProgramRTId;
        kbc.Name='T_SFLL';
        kbc.KBCExtID__c='T_PRG-000001';
        kbc.Entity__c='Imo Enterprises (IE)';
        kbc.Type__c='NA';
        kbc.Status__c='1-Backlog';
        kbc.ParentKBCard__c=null;
        insert kbc;
        parentProgramID1= kbc.id;
        System.debug('TSFLL id=' + parentProgramID1);
        
        kbc=new KBCard__c();
        kbc.RecordTypeId=ProgramRTId;
        kbc.Name='T_Another_Program';
        kbc.KBCExtID__c='T_PRG-000002';
        kbc.Entity__c='Imo Enterprises (IE)';
        kbc.Type__c='NA';
        kbc.Status__c='1-Backlog';
        kbc.ParentKBCard__c=null;
        insert kbc;
        parentProgramID2= kbc.id;
        System.debug('T_Another_Program id=' + parentProgramID2);
    }

    static testmethod void test() {  
        Test.startTest();
        KBCardProcessorHierarchyPath kbcp = new KBCardProcessorHierarchyPath();
        Id batchId = Database.executeBatch(kbcp);
        Test.stopTest();

        // after the testing stops, assert records were updated properly
        System.assertEquals(2, [select count() from KBCard__c where HierarchyPath__c != '']);
    }
}