force-app/main/default/objects/KBCard__c/KBCard__c.object-meta.xml
<CustomObject>
    <description>KanBan cards for making program, projects, epics, features, &amp; user stories</description>
    <label>KBCard</label>
    <nameField>
        <label>KBCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KBCards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KBCard__c/fields/Hierarchy_Sort_Number__c.field-meta.xml
<CustomField>
    <fullName>Hierarchy_Sort_Number__c</fullName>
    <label>Hierarchy Sort Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/Level_Number__c.field-meta.xml
<CustomField>
    <fullName>Level_Number__c</fullName>
    <label>Level Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/LineDisplay__c.field-meta.xml
<CustomField>
    <fullName>LineDisplay__c</fullName>
    <label>Line Display</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/ParentKBCard__c.field-meta.xml
<CustomField>
    <fullName>ParentKBCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent KBCard</label>
    <referenceTo>KBCard__c</referenceTo>
    <relationshipLabel>Child KBCards</relationshipLabel>
    <relationshipName>KBCards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NA</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Business Plan</fullName>
            </value>
            <value>
                <fullName>Site Build</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Operating Documents</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KBCardHierarchyMethods.cls
global class KBCardHierarchyMethods {
// KBCardHierarchyMethods.ResetHierarchy();

    static integer currentHierarchySort=0;
       
    webservice static void ResetHierarchy(){
        KBCardHierarchyMethods.IterateHierarchy(null, 0);
    }
    public static void IterateHierarchy(ID parentID, integer iLevel){
        integer currentLevel=iLevel;
        String p='';
		p=p.leftPad(currentLevel*5,'-');
        currentLevel++;
        List<KBCard__c> iterateEntities = [SELECT Id, Name, Type__c, Level_Number__c, LineDisplay__c, ParentKBCard__c FROM KBCard__c WHERE ParentKBCard__c=:parentId ORDER BY Name];
        for(KBCard__c rec : iterateEntities){
            currentHierarchySort=currentHierarchySort + 1;
			rec.Hierarchy_Sort_Number__c=currentHierarchySort;
            rec.Level_Number__c=currentLevel;
            
            if (rec.Type__c != null){
                if (rec.Type__c != 'NA'){
                    rec.LineDisplay__c=p + rec.Name + ' ' + rec.Type__c;  
                } else {
                    rec.LineDisplay__c=p + rec.Name;
                }
            } else {
                rec.LineDisplay__c=p + rec.Name;
            }
            
            update rec;
    		KBCardHierarchyMethods.IterateHierarchy(rec.Id, currentLevel);
            
        }
        
    }
}