force-app/main/default/objects/KBCard__c/KBCard__c.object-meta.xml
<CustomObject>
    <description>KanBan cards for making program, projects, epics, features, &amp; user stories</description>
    <label>KBCard</label>
    <nameField>
        <label>KBCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KBCards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KBCard__c/fields/KBCard_ID__c.field-meta.xml
<CustomField>
    <fullName>KBCard_ID__c</fullName>
    <formula>CASE( RecordType.Name , &quot;Program&quot;, &quot;PRG&quot;, &quot;Project&quot;, &quot;PRJ&quot;, &quot;Capability&quot;, &quot;CAP&quot;, &quot;Epic&quot;, &quot;EPC&quot;, &quot;Feature&quot;, &quot;FEA&quot;, &quot;Story&quot;, &quot;STO&quot; ,&quot;&quot;)  +   KBCAN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KBCard ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/KBCExtID__c.field-meta.xml
<CustomField>
    <fullName>KBCExtID__c</fullName>
    <label>KBCExtID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>CASE(  RecordType.Name  , &quot;Program&quot;, 1, &quot;Project&quot;, 2, &quot;Capability&quot;, 3, &quot;Epic&quot;, 4, &quot;Feature&quot;, 5, &quot;Story&quot;, 6, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KBCard__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <label>Program</label>
</RecordType>

force-app/main/default/classes/KBCardProcessorHierarchyPath.cls
global class KBCardProcessorHierarchyPath implements Database.Batchable <SObject> {
    global integer recordsProcessed = 0;
    
    //START METHOD
    global Database.QueryLocator start(Database.BatchableContext bc){
        Id ProgramRTId = Schema.SObjectType.KBCard__c.getRecordTypeInfosByDeveloperName().get('Program').getRecordTypeId();
        String Query='Select id, KBCard_ID__c, KBCExtID__c, Level__c, Name from KBCard__c Order by Level__c, KBCExtID__c';
        System.debug(Query);
        return Database.getQueryLocator(Query);
     
    }
    //EXECUTE METHOD
    global void execute(Database.BatchableContext bc, List<KBCard__c> scope){
        for(KBCard__c kbc : scope){
            //update record here
            System.debug('Processing Level=' + kbc.Level__c + ' KBCExtID=' + kbc.KBCard_ID__c);
            HierarchyMethods.ResetCurrentRecordHierarchyFields(kbc.Id);
            recordsProcessed=recordsProcessed+1;
        }
        try{
        	//normally update list here
        } catch(Exception e) {
            System.debug(e);
        }
    }
    //FINISH METHOD
    global void finish(Database.BatchableContext bc){
        Id job=bc.getJobId();
        System.debug(job);
        System.debug('Records processed=' + recordsProcessed);
         
    }
}