force-app/main/default/objects/KBCard__c/KBCard__c.object-meta.xml
<CustomObject>
    <description>KanBan cards for making program, projects, epics, features, &amp; user stories</description>
    <label>KBCard</label>
    <nameField>
        <label>KBCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KBCards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KBCard__c/fields/HierarchyCapability__c.field-meta.xml
<CustomField>
    <fullName>HierarchyCapability__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarchy Capability</label>
    <referenceTo>KBCard__c</referenceTo>
    <relationshipLabel>KBCards (Hierarchy Capability)</relationshipLabel>
    <relationshipName>KBCardsCapability</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/HierarchyEpic__c.field-meta.xml
<CustomField>
    <fullName>HierarchyEpic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarchy Epic</label>
    <referenceTo>KBCard__c</referenceTo>
    <relationshipLabel>KBCards (Hierarchy Epic)</relationshipLabel>
    <relationshipName>KBCardsEpic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/HierarchyFeature__c.field-meta.xml
<CustomField>
    <fullName>HierarchyFeature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarchy Feature</label>
    <referenceTo>KBCard__c</referenceTo>
    <relationshipLabel>KBCards (Hierarchy Feature)</relationshipLabel>
    <relationshipName>KBCardsFeature</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/HierarchyProgram__c.field-meta.xml
<CustomField>
    <fullName>HierarchyProgram__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarchy Program</label>
    <referenceTo>KBCard__c</referenceTo>
    <relationshipLabel>KBCards (HierarchyProgram)</relationshipLabel>
    <relationshipName>KBCardsProgram</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/HierarchyProject__c.field-meta.xml
<CustomField>
    <fullName>HierarchyProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hierarchy Project</label>
    <referenceTo>KBCard__c</referenceTo>
    <relationshipLabel>KBCards (Hierarchy Project)</relationshipLabel>
    <relationshipName>KBCardsProject</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/KBCard_ID__c.field-meta.xml
<CustomField>
    <fullName>KBCard_ID__c</fullName>
    <formula>CASE( RecordType.Name , &quot;Program&quot;, &quot;PRG&quot;, &quot;Project&quot;, &quot;PRJ&quot;, &quot;Capability&quot;, &quot;CAP&quot;, &quot;Epic&quot;, &quot;EPC&quot;, &quot;Feature&quot;, &quot;FEA&quot;, &quot;Story&quot;, &quot;STO&quot; ,&quot;&quot;)  +   KBCAN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KBCard ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/KBCExtID__c.field-meta.xml
<CustomField>
    <fullName>KBCExtID__c</fullName>
    <label>KBCExtID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <formula>CASE(  RecordType.Name  , &quot;Program&quot;, 1, &quot;Project&quot;, 2, &quot;Capability&quot;, 3, &quot;Epic&quot;, 4, &quot;Feature&quot;, 5, &quot;Story&quot;, 6, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/ParentKBCard__c.field-meta.xml
<CustomField>
    <fullName>ParentKBCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent KBCard</label>
    <referenceTo>KBCard__c</referenceTo>
    <relationshipLabel>Child KBCards</relationshipLabel>
    <relationshipName>KBCards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HierarchyMethods.cls
public class HierarchyMethods {
/* to execute
 * 
 * HierarchyMethods.ResetAllKBCardHierarchyPath();
 *
 * https://www.sfdcpoint.com/salesforce/batch-apex-example-in-salesforce/  
 * 
 * HierarchyMethods.ResetCurrentRecordHierarchyFields('a012D000003ZTuDQAW');
 * 
*/  
    public static void ResetAllKBCardHierarchyPath(){
        KBCardProcessorHierarchyPath kbcp = new KBCardProcessorHierarchyPath();
        Id batchId = Database.executeBatch(kbcp);        
    }
    
    public static void ResetCurrentRecordHierarchyFields(Id currentId){
        System.debug('here start');        
		Id parentId;
        
        KBCard__c currentkbc = New KBCard__c();
        KBCard__c updatekbc = New KBCard__c();
        updatekbc=[Select id, KBCard_ID__c, KBCExtID__c, Level__c, ParentKBCard__c, Name from KBCard__c where id=:currentId];
        currentkbc=updatekbc;
        parentId=currentkbc.ParentKBCard__c;
        System.debug('Current='+currentkbc.Name);        
        if(currentkbc.Level__c==6){
            System.debug('level 6');
            updatekbc.HierarchyFeature__c=currentkbc.ParentKBCard__c;
            update updatekbc;            
            currentkbc = New KBCard__c();            
            currentkbc=[Select id, KBCard_ID__c, KBCExtID__c, Level__c, ParentKBCard__c, Name from KBCard__c where id=:parentId];
            parentId=currentkbc.ParentKBCard__c;
        }
        if(currentkbc.Level__c==5){
            System.debug('level 5');
            updatekbc.HierarchyEpic__c=currentkbc.ParentKBCard__c;
            update updatekbc;            
            currentkbc = New KBCard__c();            
            currentkbc=[Select id, KBCard_ID__c, KBCExtID__c, Level__c, ParentKBCard__c, Name from KBCard__c where id=:parentId];
            parentId=currentkbc.ParentKBCard__c;
        }
        if(currentkbc.Level__c==4){
            System.debug('level 4');
            updatekbc.HierarchyCapability__c=currentkbc.ParentKBCard__c;
            update updatekbc;            
            currentkbc = New KBCard__c();            
            currentkbc=[Select id, KBCard_ID__c, KBCExtID__c, Level__c, ParentKBCard__c, Name from KBCard__c where id=:parentId];
            parentId=currentkbc.ParentKBCard__c;
        }
        if(currentkbc.Level__c==3){
            System.debug('level 3');
            updatekbc.HierarchyProject__c=currentkbc.ParentKBCard__c;
            update updatekbc;            
            currentkbc = New KBCard__c();            
            currentkbc=[Select id, KBCard_ID__c, KBCExtID__c, Level__c, ParentKBCard__c, Name from KBCard__c where id=:parentId];
            parentId=currentkbc.ParentKBCard__c;
        }   
        if(currentkbc.Level__c==2){
            System.debug('level 2');
            updatekbc.HierarchyProgram__c=currentkbc.ParentKBCard__c;
            update updatekbc;
            currentkbc = New KBCard__c();            
            currentkbc=[Select id, KBCard_ID__c, KBCExtID__c, Level__c, ParentKBCard__c, Name from KBCard__c where id=:parentId];
            parentId=currentkbc.ParentKBCard__c;
        }                         
    }
}