force-app/main/default/objects/KBCard__c/KBCard__c.object-meta.xml
<CustomObject>
    <description>KanBan cards for making program, projects, epics, features, &amp; user stories</description>
    <label>KBCard</label>
    <nameField>
        <label>KBCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KBCards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KBCard__c/fields/KBCard_ID__c.field-meta.xml
<CustomField>
    <fullName>KBCard_ID__c</fullName>
    <formula>CASE( RecordType.Name , &quot;Program&quot;, &quot;PRG&quot;, &quot;Project&quot;, &quot;PRJ&quot;, &quot;Capability&quot;, &quot;CAP&quot;, &quot;Epic&quot;, &quot;EPC&quot;, &quot;Feature&quot;, &quot;FEA&quot;, &quot;Story&quot;, &quot;STO&quot; ,&quot;&quot;)  +   KBCAN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>KBCard ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/KBCExtID__c.field-meta.xml
<CustomField>
    <fullName>KBCExtID__c</fullName>
    <label>KBCExtID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KBCard__c/fields/ParentKBCard__c.field-meta.xml
<CustomField>
    <fullName>ParentKBCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent KBCard</label>
    <referenceTo>KBCard__c</referenceTo>
    <relationshipLabel>Child KBCards</relationshipLabel>
    <relationshipName>KBCards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KBCard__c/recordTypes/Capability.recordType-meta.xml
<RecordType>
    <fullName>Capability</fullName>
    <active>true</active>
    <label>Capability</label>
</RecordType>

force-app/main/default/objects/KBCard__c/recordTypes/Epic.recordType-meta.xml
<RecordType>
    <fullName>Epic</fullName>
    <active>true</active>
    <label>Epic</label>
</RecordType>

force-app/main/default/objects/KBCard__c/recordTypes/Feature.recordType-meta.xml
<RecordType>
    <fullName>Feature</fullName>
    <active>true</active>
    <label>Feature</label>
</RecordType>

force-app/main/default/objects/KBCard__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <label>Program</label>
</RecordType>

force-app/main/default/objects/KBCard__c/recordTypes/Project.recordType-meta.xml
<RecordType>
    <fullName>Project</fullName>
    <active>true</active>
    <label>Project</label>
</RecordType>

force-app/main/default/objects/KBCard__c/recordTypes/Story.recordType-meta.xml
<RecordType>
    <fullName>Story</fullName>
    <active>true</active>
    <label>Story</label>
</RecordType>

force-app/main/default/classes/TestKBCardTrigger.cls
@isTest
public class TestKBCardTrigger {

    @isTest static void TestKBCardTriggerAfterInsertAndUpdate(){
        //Set up the test first
   		Id ProgramRTId = Schema.SObjectType.KBCard__c.getRecordTypeInfosByDeveloperName().get('Program').getRecordTypeId();
        Id ProjectRTId = Schema.SObjectType.KBCard__c.getRecordTypeInfosByDeveloperName().get('Project').getRecordTypeId();
        Id CapabilityRTId = Schema.SObjectType.KBCard__c.getRecordTypeInfosByDeveloperName().get('Capability').getRecordTypeId();
        Id EpicRTId = Schema.SObjectType.KBCard__c.getRecordTypeInfosByDeveloperName().get('Epic').getRecordTypeId();
        Id FeatureRTId = Schema.SObjectType.KBCard__c.getRecordTypeInfosByDeveloperName().get('Feature').getRecordTypeId();
        Id StoryRTId = Schema.SObjectType.KBCard__c.getRecordTypeInfosByDeveloperName().get('Story').getRecordTypeId();
            
        //Run the Test on Insert        
        Test.startTest();
        //Put in a full Hierarchy for best test coverage
        //Create the parent program
        KBCard__c kbcprogram = new KBCard__c(Name='TestKBCardTrigger_Program', RecordTypeId=ProgramRTId);
        insert kbcprogram;
        KBCard__c kbcproject = new KBCard__c(Name='TestKBCardTrigger_Project', RecordTypeId=ProjectRTId, ParentKBCard__c=kbcprogram.id);
        insert kbcproject;
        KBCard__c kbccapability = new KBCard__c(Name='TestKBCardTrigger_Capability', RecordTypeId=CapabilityRTId, ParentKBCard__c=kbcproject.id);
        insert kbccapability;
        KBCard__c kbcepic = new KBCard__c(Name='TestKBCardTrigger_Epic', RecordTypeId=EpicRTId, ParentKBCard__c=kbccapability.id);
        insert kbcepic;
        KBCard__c kbcfeature = new KBCard__c(Name='TestKBCardTrigger_Feature', RecordTypeId=FeatureRTId, ParentKBCard__c=kbcepic.id);
        insert kbcfeature;
        KBCard__c kbc = new KBCard__c(Name='TestKBCardTrigger_Story', RecordTypeId=StoryRTId, ParentKBCard__c=kbcfeature.id);
        insert kbc;
        
        //Verify the Result TestKBCardOnInsert
        System.assert(true,'TestKBCardOnInsert');
        System.assertEquals(kbc.KBCard_ID__c, kbc.KBCExtID__c);

        //Run the Test on Update
        kbc.KBCExtID__c=null;
        update kbc;
        Test.stopTest();

        //Verify the Result TestKBCardOnUpdate
        System.assert(true,'TestKBCardOnUpdate');
        System.assertEquals(kbc.KBCard_ID__c, kbc.KBCExtID__c);
    }
        
}